site_name: My Docs
theme:
  name: material

plugins:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null

extra:
  version:
    provider: mike
